spring.application.name=collab-task
server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/collab_task_db
 feature/auth-roles
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.username=openpg
spring.datasource.password=openpgpwd
develop

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jackson.serialization.write-dates-as-timestamps=false

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
 feature/auth-roles
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

groq.api.key=${GROQ_API_KEY:}
groq.model=${GROQ_MODEL:llama-3.1-8b-instant}
 develop
